### PR TITLE
Added Font Awesome icon mapping.

### PR DESCRIPTION
**Pull request by Kathrin84**
I added this, so that the icon can be displayed by a Font Awesome icon which leads to the same representation (especially) color with the other Atto icons from Moodle core.

### CODE REVIEW

**Comment by sharpchi** [comment]
I second this, as we modify our colours

**Comment by abias** [comment]
Hi @damyon 

I am sure that you are busy with critical topics. But would you mind to review and merge this small and useful pull request anytime soon?

Thanks,
Alex

**Comment by abias** [comment]
As far as I see, this PR has been merged outside Github in 11e997cc5799df1d9b0bc57fd5cbf1d5942c2264, so it probably can be closed

**Comment by damyon** [comment]
Thanks

**Pull request closed without merging**
