### PR TITLE
Add GDPR declaration

### PR DESCRIPTION
**Pull request by sharpchi**
It doesn't look like your plugin stores any data, so I've implemented a null provider.

### CODE REVIEW

**Comment by abias** [comment]
Hi @damyon 

I am sure that you are busy with critical topics. But would you mind to review and merge this small and useful pull request anytime soon?

Thanks,
Alex

**Comment by abias** [comment]
As far as I see, this PR has been merged outside Github in 1c40b70e7170ce96e8486400120a5a8fd0b3537b, so it probably can be closed

**Comment by damyon** [comment]
Thanks

**Comment by paulholden** [comment]
The Privacy API implementation added here doesn't work in Moodle 3.3 with PHP 5.6 - I created #5 to address that

**Pull request closed without merging**
